### ISSUE TITLE
UI Features towards Beta v0.0.1

### ISSUE THREAD

**Issue by allankoechke** [codeartstudios/digistore-app#10]
# Important Features
## UI
- [x] #4 : Checkout flow update
- [x] #12: Supplier Management/Stock updates/Product Inventory
- [x] Admin Features
- [x] #19
- [x] #18
- [x] #17
- [x] #22
- [x] #23
- [x] #25
- [x] #30
- [x] #31

## Testing
- [ ] #34
- [ ] #35
- [ ] #36

## System
- [x] #16
- [x] Row-level authentication setup on Db (currently open to all). Depends on #17 completion first.

# Additional Features
## System
- [ ] #37
